version: '3.8'

services:
  postgres_db:
    image: postgres:17 
    container_name: itproject_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: ITProjectDb      
    ports:
      - "5432:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data 
    restart: unless-stopped 

volumes:
  pgdata: 